services:
    coresphere_console.controller:
        class: CoreSphere\ConsoleBundle\Controller\ConsoleController
        arguments:
            - "@templating"
            - "@coresphere_console.queue_executer"
            - "@coresphere_console.symfony_executer"
            - "@coresphere_console.process_executer"
            - "@coresphere_console.application"
            - "@session"
            - "%kernel.environment%"
            - "%queue_dir%"
        public: true

    coresphere_console.symfony_executer:
        class: CoreSphere\ConsoleBundle\Executer\SymfonyCommandExecuter
        arguments:
            - "@kernel"
        public: true

    coresphere_console.queue_executer:
        class: CoreSphere\ConsoleBundle\Executer\QueueCommandExecuter
        arguments:
            - "@kernel"
            - "@session"
            - "%queue_dir%"
            - "@translator"
        public: true

    coresphere_console.process_executer:
        class: CoreSphere\ConsoleBundle\Executer\ProcessCommandExecuter
        arguments:
            - "@kernel"
        public: true

    coresphere_console.routing:
        class: CoreSphere\ConsoleBundle\Routing\Loader
        arguments:
            - "@routing.loader.yml"
        public: true
        tags:
            - { name: routing.loader }

    coresphere_console.toolbar:
        class: CoreSphere\ConsoleBundle\DataCollector\DataCollector
        public: true
        tags:
            - { name: data_collector, template: "CoreSphereConsoleBundle:Toolbar:toolbar", id: "coresphere_console" }

    # console application
    coresphere_console.application.factory:
        class: CoreSphere\ConsoleBundle\Console\ApplicationFactory
        public: true

    coresphere_console.application:
        class: Symfony\Bundle\FrameworkBundle\Console\Application
        factory: ["@coresphere_console.application.factory", create]
        arguments:
            - "@kernel"
        public: true

    coresphere_console.command:
        class: CoreSphere\ConsoleBundle\Command\ConsoleExecuteCommand
        arguments:
            - "@kernel"
            - "@coresphere_console.symfony_executer"
            - "@coresphere_console.process_executer"
            - "%queue_dir%"
        tags:
            - { name: 'console.command' }

parameters:
    queue_dir: "/tmp/coresphere_console"
