console:
    path:  /_console
    defaults: { _controller: coresphere_console.controller:consoleAction }
    methods: [GET]

console_exec:
    path:  /_console/commands.{_format}
    defaults: { _controller: coresphere_console.controller:execAction, _format: json }
    methods: [POST]
    requirements:
        _format: json
