# .github/workflows/code_coverage.yaml
name: Code_Coverage

on: ["push", "pull_request"]

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: pcov

      - run: composer install --no-progress

      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - uses: codecov/codecov-action@v1.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/logs/clover.xml
